name: Pull Request Workflow

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main

jobs:
  pull_request_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Run ESLint check
        run: yarn lint

      - name: Run Prettier check
        run: yarn format-check

      - name: Run type check
        run: yarn type-check

      - name: Run tests
        run: yarn test

      - name: Build dry run
        run: yarn build
